version: '3'
services:
  frontend:
    image: hawksdev/yolo-client-g3:1.0.0
    depends_on:
      - backend
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      yolo-g3-network:
        ipv4_address: 172.20.0.4
  backend:
    image: hawksdev/yolo-backend-g3:1.0.0
    environment:
      MONGODB_URI: 'mongodb://group-3:group-3@172.20.0.2:27017'
      PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      yolo-g3-network:
        ipv4_address: 172.20.0.3
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: group-3
      MONGO_INITDB_ROOT_PASSWORD: group-3
    ports:
      - 27017:27017
    networks:
      yolo-g3-network:
        ipv4_address: 172.20.0.2

networks:
  yolo-g3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16